version: '3.3'

services:
   web:
      image: ghcr.io/shanelkapramuditha/python-ci-cd:dev
      container_name: python-ci-cd-dev
      restart: unless-stopped

      ports:
         - '5000:5000'
      env_file:
         - stack.env

volumes:
   web:
      name: 'python-ci-cd-dev'
