name: Build Docker Container

on:
   push:
      branches:
         - main
         - dev

jobs:
   docker:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - name: Check out the repository
           uses: actions/checkout@v2

         - name: Log in to the Container Registry
           run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

         - name: Set Up QEMU
           uses: docker/setup-qemu-action@v2

         - name: Set Up Docker Buildx
           uses: docker/setup-buildx-action@v2
