name: Build Docker Container

on:
   push:
      branches:
         - main

jobs:
   docker:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - name: Check out the repository
           uses: actions/checkout@v2

         - name: Log in to the Container Registry
           run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

         - name: Set Up QEMU
           uses: docker/setup-qemu-action@v2

         - name: Set Up Docker Buildx
           uses: docker/setup-buildx-action@v2

         - name: Convert Username and Repository Name to lowercase
           run: |
              echo "export REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
              echo "USERNAME=${${{ github.actor}},,}" >> $GITHUB_ENV
              # Print the values
              echo $REPOSITORY
              echo $USERNAME

         - name: Build and push
           uses: docker/build-push-action@v2
           with:
              context: .
              file: ./docker/dev/Dockerfile
              push: true
              tags: ghcr.io${{ env.USERNAME }}/${{ github.repository }}:dev
              platforms: linux/amd64,linux/arm64
